name: octaviOS Build
permissions: write-all
on:
    workflow_dispatch:
        inputs:
            device:
                description: 'Device'
                required: true
                default: 'vayu'
                type: choice
                options:
                - vayu
            cleanstrategy:
                description: 'Select Clean strategy'
                required: true
                default: 'no'
                type: choice
                options:
                - nope
                - installclean
                - clobber
jobs:
    riceDroid-Build:
      runs-on: self-hosted
      if: ${{ inputs.device }}
      steps:
        - name: Verify the environment
          run: |
            if [ $UID -eq 0 ]; then echo "Running as root, aborting"; exit 1; else echo "Running as $USER"; fi
        - name: Get current date
          id: date
          run: |
            echo "::set-output name=date::$(date +'%Y-%m-%d--%H-%M-%S')"
        - name: Clean Workspace
          run: | 
            rm -f ${GITHUB_WORKSPACE}/OctaviOS*.zip*
        - name: Clean Strategy
          run: | 
           cd ~/octavi/
           if [[ $cleanstrategy == "installclean" ]]; then echo "Make install clean";  
           source build/envsetup.sh && lunch lineage_${{ inputs.device }}-userdebug && make installclean;
           elif [[ $cleanstrategy == "clobber" ]];  then echo "Make clobber";
           source build/envsetup.sh && lunch lineage_${{ inputs.device }}-userdebug $$ make clobber;
           elif [[ $cleanstrategy == "nope" ]];  then echo "DIRTY BUILD";
           fi
        - name: Run the build
          run: |
            cd ~/octavi/
            echo "Building for ${{ inputs.device }}"

            source build/envsetup.sh
            lunch lineage_${{ inputs.device }}-userdebug
            mka bacon -j$(nproc --all)
            cp out/target/product/${{ inputs.device }}/OctaviOS*.zip* ${GITHUB_WORKSPACE}
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            title: "octavi Build"
            prerelease: false
            automatic_release_tag: "${{ inputs.device }}-${{ steps.date.outputs.date }}"
            files: |
                OctaviOS*.zip*
